### ISSUE TITLE
Definizioni, acronimi e abbreviazioni

### ISSUE THREAD

**Issue by Andrea-Augello** [Andrea-Augello/SviluppoSW#10]
La sezione dell'introduzione su abbreviazioni, definizioni ed acronimi va ampliata _abbondantemente_

**Comment by Carlo-Cafaro** [comment]
Per completare la tabella devo creare un branch con pull annessa o modifico direttamente il master?

**Comment by Andrea-Augello** [comment]
Vai nel master, non è particolarmente importante

**Comment by Carlo-Cafaro** [comment]
Completata la tabella, se non vi vengono in mente altre definizioni direi di chiudere l'issue

**Comment by Carlo-Cafaro** [comment]
La tabella è completa e definitiva.
