### ISSUE TITLE
Scegliere un modello architetturale

### ISSUE THREAD

**Issue by Andrea-Augello** [Andrea-Augello/SviluppoSW#11]

**Comment by Carlo-Cafaro** [comment]
La cosa più sensata (e facile) in questo momento è essere propensi ad usare una Client - Server. Che ne dite voi?

**Comment by Andrea-Augello** [comment]
Io penso ad una roba che ha di mezzo una struttura a layer, ma al momento è prematuro preoccuparcene

**Comment by Carlo-Cafaro** [comment]
L'architettura scelta per il progetto è quella a layer.
