### ISSUE TITLE
Scelta nome

### ISSUE THREAD

**Issue by Andrea-Augello** [Andrea-Augello/SviluppoSW#18]
Nel file [Proposte acronimi](https://github.com/Andrea-Augello/SviluppoSW/blob/master/Proposte%20acronimi.md) ho messo un po' di acronimi possibili che mi sono venuti in mente, sarebbe simpy non chiamarlo sempre "il sistema"

Voti:
SPRINT:  2
PAPER:   1
PERA:    -1

**Comment by Frankie690II** [comment]
SPRINT mi piace, lo voto.

**Comment by Frankie690II** [comment]
PERA direi di evitarlo

**Comment by Andrea-Augello** [comment]
Ne ho aggiunti un altro po'

**Comment by Carlo-Cafaro** [comment]
I miei voti vanno a SPRINT e PAPER

**Comment by Carlo-Cafaro** [comment]
Se nessuno obietta o vota qualcos'altro in un'ora ritengo che l'issue possa essere chiuso

**Comment by Andrea-Augello** [comment]
E vince SPRINT
