### ISSUE TITLE
Interfaccia utente: navigazione e mock-up

### ISSUE THREAD

**Issue by Andrea-Augello** [Andrea-Augello/SviluppoSW#25]
L'ultima sezione del rad va riempita con i mock-up del software

L'idea sarebbe di mostrare le varie schermate che vanno spuntando in ogni caso d'uso in sequenza (Sarebbe carino in una GIF, però poi nel pdf si perde).  
Il minimo indispensabile è che ci siano perlomeno le schermate più importanti.  
I vari mockup (preferibilmente con nome file descrittivi) vanno messi in [questa cartella](https://github.com/Andrea-Augello/SviluppoSW/tree/Mock-up/docs/media/mock-up) che sta in un branch apposito per i mockup. 

Nota: i mock-up **non** devono essere screenshot del software, vanno fatti prima e poi il software va modellato di conseguenza.

**Comment by Carlo-Cafaro** [comment]
Mock-up completati. Offerti da me, grazie arrivederci
