### ISSUE TITLE
Corporate BS

### ISSUE THREAD

**Issue by Andrea-Augello** [Andrea-Augello/SviluppoSW#3]
La sezione 1 del [__RAD__](https://github.com/Andrea-Augello/SviluppoSW/blob/master/docs/RAD.md#1-introduzione) consiste quasi esclusivamente di roba che esula dall'ingegneria, i punti 1.1 e 1.2 possono essere compilati in qualunque momento senza particolare sforzo intellettuale

**Comment by Frankie690II** [comment]
Ho aperto una pull
