### ISSUE TITLE
Dettagli del sistema corrente

### ISSUE THREAD

**Issue by Andrea-Augello** [Andrea-Augello/SviluppoSW#5]
È necessario avere (e aggiungere nel rad) un'idea chiara di come funziona esattamente l'ospedale che andremo ad automatizzare

**Comment by Carlo-Cafaro** [comment]
Credo che ormai siamo in possesso di quasi tutti gli elementi circa il funzionamento del software. L'issue verrà chiuso al completamento del RAD

**Comment by Andrea-Augello** [comment]
La questione qua però non è come funziona il software, ma come funziona l'ospedale che andiamo ad informatizzare
