### ISSUE TITLE
Diagrammi dei casi d'uso

### ISSUE THREAD

**Issue by Andrea-Augello** [Andrea-Augello/SviluppoSW#7]
Con [astah](http://astah.net/student-license-request) vanno creati i diagrammi dei casi d'uso, tra i documenti c'è il file con tutti diagrammi fatti fino ad ora

- [x] Diagramma di alto livello
- [x] CreaPrenotazione
- [x] ModificaPrenotazione
- [x] Visualizza FSE
- [ ] InserisciDettagliVisita
- [ ] NotificaPrenotazione
- [x] EffettuaAutenticazione

**Comment by Carlo-Cafaro** [comment]
Modificata e aggiornata la piccola to-do list relativa a questa issue

**Comment by Andrea-Augello** [comment]
UPDATE: le modifiche dovranno essere meno drastiche del previsto, vanno però riviste delle precondizioni
